### ISSUE TITLE
Replace all references to xrOS in availability attributes to visionOS

### ISSUE THREAD

**Issue by edorphy** [ChimeHQ/Meter#10]
Update all references to xrOS to visionOS.

<img width="265" alt="Screenshot 2024-02-03 at 1 09 46 PM" src="https://github.com/ChimeHQ/Meter/assets/1335272/0064e1ff-908e-42fc-a44f-9f60e32b1a96">

**Comment by mattmassicotte** [comment]
Thanks for reporting this - should be all fixed up!
