### ISSUE TITLE
subFrames vs. flattenedFrames

### ISSUE THREAD

**Issue by michaeleisel** [ChimeHQ/Meter#4]
According to Apple, for subFrames, "there can be many levels of nested stack frames". It seems that this just gets flattened with flattenedFrames in this library, but why is there nesting in the first place? Isn't it really just a simple flat stack trace?

**Comment by mattmassicotte** [comment]
Hello!

This is a good question, and something I was confused about at first as well. I think it will become clearer why `flattenedFrames` is useful by taking a look at a [real MetricKit payload](https://github.com/ChimeHQ/Meter/blob/main/MeterTests/Resources/real_report.json).

The `CallStackTree` structure is able to describe more than just traditional stack traces. In my opinion, it's a very cumbersome API, but its what we have. This method just makes it easier to get a plain array of frames, which is often what you really want when interacting with MetricKit data.

**Comment by michaeleisel** [comment]
Wow, that's a pretty wild nesting. Yes, agreed that a flattened structure is nicer. Thanks for the clarification!
