### ISSUE TITLE
What is the License / Source of the BinaryImage files?

### ISSUE THREAD

**Issue by SwiftNativeDeveloper** [ChimeHQ/Meter#6]
@mattmassicotte the BinaryImage files do not contain a header with your name. I was curious what the source of them is and what the license of the files is?

I would have to know this to use your library, but the on-device symbolication is quite slick especially if done during a background processing task or something like. Since Apple explicitly states in their videos symbolication is to take place off device, it seems like a happy compromise that would be an accepted solution by them.

**Comment by mattmassicotte** [comment]
The license covering these is the one at the root. My intention is for it to cover the entire repo.

I had assumed that was implied, but perhaps I'm wrong. Do you think each file need its own explicit license reference?

The general technique used for this symbolication process uses only public API, and is used by other crash reporting services. So should be 100% App Store-compatible!

**Comment by SwiftNativeDeveloper** [comment]
@mattmassicotte since it didn't have the header I wasn't sure if you were the author or if you pulled it from somewhere else that would potentially have its own license or be updated outside of this SPM.

I let SwiftLint find these things for me when the headers don't match the code. The following header style was not in BinaryImage.h / .m

//
//  CallStackTree.swift
//  Meter
//
//  Created by Matt Massicotte on 2020-06-30.
//

**Comment by mattmassicotte** [comment]
Yeah, I began removing the header comment from new files a while ago. But, I typically don't go back to remove pre-existing ones unless I work in the file. Very sorry about the confusion!

**Comment by mattmassicotte** [comment]
Hope this is now all resolved!
